_target_: genpp.models.loss.MultiPatchwiseRBFScore
lengthscales: ${eval:'[[i*ps**2 for i in [0.5, 1.0, 2.0]] for ps in ${.patch_sizes}]'}
patch_sizes:
  - 3
  - 5
  - 7
height: ${data.spatial.original.longitude}
width: ${data.spatial.original.latitude}
