# CNN-based Chen Model Configuration
_target_: genpp.models.chen.CNNChenModel

# Model architecture parameters
in_features: ${data.variables.input_variables}
meta_features: ${data.variables.meta_features}
out_features: ${data.variables.output}
height: ${data.spatial.padded.longitude}
width: ${data.spatial.padded.latitude}
noise_dim: 5 # Every gridpoint has noise added of noise_dim
embedding_dim: 5
n_samples_train: 50
padding: ${data.spatial.padding_list}

# Training parameters
lr: 5e-2

# Activation function
final_activation:
  _target_: genpp.models.layers.FinalActivation
  activations:
    # TODO we might want to force this to be positive
    - _target_: torch.nn.Identity # Temperature (normalized)
    - _target_: torch.nn.Identity # Wind speed (normalized)

# Loss function
loss_fn:
  _target_: genpp.models.loss.EnergyScore
  beta: 1.0
  clamp: true
  mean: true

# Optimizer
optimizer: ${class:torch.optim.AdamW}

# Scheduler
lr_scheduler: ${class:torch.optim.lr_scheduler.OneCycleLR}
lr_scheduler_kwargs:
  max_lr: ${model.lr}
  epochs: 100
  steps_per_epoch: 273
  pct_start: 0.1

lr_scheduler_update_kwargs:
  interval: "step"
  frequency: 1
