# CNN-based Chen Model Configuration
_target_: genpp.models.chen.CNNChenModel

# Model architecture parameters
in_features: ${data.variables.input_variables}
meta_features: ${data.variables.meta_features}
out_features: ${data.variables.output}
height: ${data.spatial.padded.longitude}
width: ${data.spatial.padded.latitude}
noise_dim: 5 # Every gridpoint has noise added of noise_dim
embedding_dim: 5
n_samples_train: 50
padding: ${data.spatial.padding_list}

# Activation function
final_activation:
  _target_: genpp.models.layers.FinalActivation
  activations:
    # TODO we might want to force this to be positive -> Or not since the values are standardized
    # Fix use min max normalization for Wind speed -> Use softplus/relu then
    - _target_: torch.nn.Identity # Temperature (standardized)
    - _target_: torch.nn.Identity # Wind speed (standardized)

# Loss function
loss_fn:
  _target_: genpp.models.loss.EnergyScore
  beta: 1.0
  clamp: true

# Optimizer and learning rate scheduler are imported automatically due to the folder structure
