# CNN-based Chen Model Configuration
defaults:
  - _self_

_target_: genpp.models.chen.CNNChenModel

# Model architecture parameters
in_features: 63  # From variables.input_concat
meta_features: 5  # From variables.meta_features
out_features: 2  # From variables.output
width: 43   # From spatial.padded.longitude
height: 32   # From spatial.padded.latitude
noise_dim: 1 # Every gridpoint has noise added of noise_dim
embedding_dim: 5
n_samples_train: 50
padding: ${data.spatial.padding_list}

# Training parameters
lr: 3e-4

# Activation function
final_activation:
  _target_: genpp.models.layers.FinalActivation
  activations:
    - _target_: torch.nn.Identity # Temperature
    - _target_: torch.nn.ReLU # Wind speed

# Loss function
loss_fn:
  _target_: genpp.models.loss.EnergyScore
  beta: 1.0
  clamp: true
  mean: false

# Optimizer
optimizer: torch.optim.AdamW
