# DRN model config
_target_: genpp.models.distributionalRegression.DRNModel

in_features: ${data.features.input_concat}
out_distribution:
  _target_: genpp.models.distributionalRegression.distributions.PredictiveCombinedDistribution
  _partial_: true # we need to pass the rescalers to it
hidden_channels:
  - 256
  - 128
  - 64
height: ${data.spatial.original.longitude}
width: ${data.spatial.original.latitude}
embedding_dim: 5
td_embedding_dim: 4
normalize: true
use_rescaler: true

# Optimizer and learning rate scheduler are imported automatically due to the folder structure
