defaults:
  - engression

# Loss function is now Patchwise Energy Score instead of standard Energy Score
loss_fn:
  _target_: genpp.models.loss.PatchwiseEnergyScore
  beta: 1.0
  clamp: true
  patch_size: 3
  height: ${data.spatial.original.longitude}
  width: ${data.spatial.original.latitude}

# Optimizer and learning rate scheduler are imported automatically due to the folder structure
