# UNet-based Flow Matching Model Configuration
_target_: genpp.models.fm.base.FlowMatchingModel
n_samples: 50
solver_iter: 10
padding: ${data.spatial.padding_list}
use_rescaler: false  # Whether to use rescalers from the datamodule
internal_td_scaling:
  _target_: genpp.models.utils.LinearTDScaling
  mode: abs

# Model backbone parameters
backbone:
  _target_: genpp.models.fm.fm_uvit.UViT
  img_height: ${data.spatial.padded.longitude}
  img_width: ${data.spatial.padded.latitude}
  patch_size_height: 4
  patch_size_width: 4
  in_channels: ${data.features.output} # this is x, the variable to be predicted
  embed_dim: 4 * 4 * 2
  depth: 2
  num_heads: 4
  mlp_ratio: 4.0
  qkv_bias: False
  qk_scale: None
  norm_layer: nn.LayerNorm
  conv: True
  skip: True

  channels_conditioning: ${data.features.input_concat} # y is the conditioning variable here

# Optimizer and learning rate scheduler are imported automatically due to the folder structure
