# Main configuration file for AutoEncoder training (FID)
defaults:
  - data/dataloader: standard
  - data/spatial: standard
  - data/splits: standard
  - data/preprocess: none
  - data: weatherbench2_cut_fast
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: AUTOENCODER(FID)
seed: 42

# Model hyperparameters
model:
  _target_: genpp.eval.FID.autoencoder.AutoEncoder
  in_channels: 2   # Number of input channels
  padding: [4, 5, 2, 1]  # Pad so that the size is 40 x 40
  latent_dim: 128  # Latent dimension for the autoencoder
  use_rescaler: False # For compatibility with other models


logger:
  tags:
    - "test"
    - "fid"
    - "autoencoder"
