# Main configuration file for GenPP training
defaults:
  - base_chen
  - override model: cnn_chen_spatial
  - _self_

name: CHEN_SPATIAL
seed: 42

logger:
  tags:
    - "test"
    - "cnn"
    - "chen"
    - "multi leadtime"
