# Main configuration file for Classifier training (FID)
defaults:
  - data/dataloader: simple
  - data/weatherbench2/splits: standard
  - data: weatherbench2/classification_dataset
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model: classifierencoder
  - trainer: fast
  - logger: wandb
  - hydra: standard
  - _self_

name: CLASSIFIER(FID)
seed: 42

logger:
  tags:
    - "test"
    - "fid"
    - "classifier"
