# Main configuration file for GenPP training
defaults:
  - data/dataloader: standard
  - data: wb2_full_minmax
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model: drn
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: DRN
seed: 42

logger:
  tags:
    - ${hydra:runtime.choices.data}
    - ${hydra:runtime.choices.model}
    - ${oc.env:USER}
