# Main configuration file for GenPP training
defaults:
  - data/dataloader: standard
  - data/spatial: padded_x
  - data/splits: standard
  - data/preprocess: standard
  - data: weatherbench2_full_fast
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model: cnn_chen
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: CHEN
seed: 42

logger:
  tags:
    - "test"
    - "cnn"
    - "chen"
    - "multi leadtime"
