# Main configuration file for GenPP training
defaults:
  - data/dataloader: standard
  - data/spatial: padded_xy
  - data/splits: standard
  - data/preprocess: standard
  - data: weatherbench2_full_fast
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model: fm_uvit_direct
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: FM_UVIT
seed: 42

logger:
  tags:
    - ${hydra:runtime.choices.data}
    - ${hydra:runtime.choices.model}
