# Main configuration file for GenPP training
defaults:
  - data/dataloader: standard
  - data: wb2_cut
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model: emos
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: EMOS
seed: 42

logger:
  tags:
    - ${hydra:runtime.choices.data}
    - ${hydra:runtime.choices.model}
