# Main configuration file for GenPP training
defaults:
  - data/dataloader: standard
  - data/spatial: standard
  - data/splits: standard
  - data/preprocess: minMaxWind
  - data: weatherbench2_full_fast
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model: drn
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: DRN
seed: 42

logger:
  tags:
    - "test"
    - "drn"
