# Main configuration file for GenPP training
defaults:
  - data/dataloader: standard
  - data: wb2_full_pad_x
  - model/optimizer: adamW
  - model/lr_scheduler: constant
  - model/loss_fn: energy_score
  - model: cnn_chen_direct
  - trainer: default
  - logger: wandb
  - hydra: standard
  - _self_

name: CHEN
seed: 42

logger:
  tags:
    - ${hydra:runtime.choices.data}
    - ${hydra:runtime.choices.model/loss_fn}
    - ${hydra:runtime.choices.model}
