# Main configuration file for GenPP training
defaults:
  - data: weatherbench2
  - model: cnn_chen
  - trainer: default
  - logger: default
  - _self_

seed: 42

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
