# Standard time splits for WeatherBench2
train:
  _target_: builtins.slice
  start: "2018-01-03"
  stop: "2020-12-31"
val:
  _target_: builtins.slice
  start: "2021-01-01"
  stop: "2021-12-31"
test:
  _target_: builtins.slice
  start: "2022-01-01"
  stop: "2022-12-31"
